### PR TITLE
feat!: Control panel to manage cookie banner settings

### PR DESCRIPTION
**Pull request by giuliaghisini**
Schermata 2023-12-15 alle 13 35 46

### CODE REVIEW

**Comment by ichim-david** [comment]
@giuliaghisini I'm trying your pull request and I get the following error
slate-error
If I set undefined here
https://github.com/collective/volto-gdpr-privacy/pull/19/files#diff-3459a7e40307a8ca578eb78b2fc40c2f75381892065783ad8ac3ccace8cde704R48
and here https://github.com/collective/volto-gdpr-privacy/pull/19/files#diff-888f187bd9856bacbf2ec5ddd0ef8828462835bfdbc233f3d08e9fa9beafa0efR21
then the slate will create a default value and it won't complain that you've set {} which is not a slate element

I tested afterward to edit the content or use the default and it works
cookie-policy

Got a problem with adding the commit to remove the {} or if I add this commit?

**Comment by giuliaghisini** [comment]
@ichim-david sorry for the delay, i've fixed it setting undefined instead {}, could you try it now?

**Comment by ichim-david** [comment]
> @ichim-david sorry for the delay, i've fixed it setting undefined instead {}, could you try it now?

@giuliaghisini yup this fixes is as it applies my suggestion, thank you.

**Comment by ichim-david** [comment]
@giuliaghisini what's holding this pull request from being merged into master?
This feature is good enough and needed enough to warrant a merge and release.
You can always improve further in further releases or get bug reports after things are merged.
If something isn't released it won't be checked by other developers so having it  as a branch
greatly limits it's potential and usage.
Please consider my suggestion and if there is any blockers add a comment so that we can
see if we can help out with them.

**Comment by giuliaghisini** [comment]
> @giuliaghisini what's holding this pull request from being merged into master? This feature is good enough and needed enough to warrant a merge and release. You can always improve further in further releases or get bug reports after things are merged. If something isn't released it won't be checked by other developers so having it as a branch greatly limits it's potential and usage. Please consider my suggestion and if there is any blockers add a comment so that we can see if we can help out with them.

We planned to merge it in next weeks! We will inform you when it's done

**Pull request merged**
